=== shubham-aakarsh/APPDEV-LAB/lab3b/b.dtd
<!ELEMENT pets (pet+)>
<!ELEMENT pet (name, age, type, color)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT color (#PCDATA)>




 Write the DTD for the following XML document. 
 
 
      <Books> 
 <Book> 
 <Isbn> 0 – 8447 – 768 </Isbn> 
 <Title> XML in a Nutshell </Title> 
 <Author> Harold, Elliotte Rusty </Author> 
 </Book> 
  <Book> 
  <Isbn> 978 – 81 – 317 – 6235 – 6 </Isbn> 
  <Title> Service – Oriented Architecture </Title> 
  <Author> Thomas Erl </Author> 
  </Book> 
   <Book> 
   <Isbn> 978 – 81 – 317 – 1869 – 8 </Isbn> 
   <Title> XML and WebServices </Title> 
   <Author> Ron Schmelzer </Author> 
   </Book> 
   </Books>

=== shubham-aakarsh/APPDEV-LAB/lab3b/b.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pets SYSTEM "b.dtd">
<pets>
    <pet>
        <name>Tilly</name>
        <age>14</age>
        <type>cat</type>
        <color>silver</color>
    </pet>
    <pet>
        <name>Amanda</name>
        <age>10</age>
        <type>dog</type>
        <color>brown</color>
    </pet>
    <pet>
        <name>Jack</name>
        <age>3</age>
        <type>cat</type>
        <color>black</color>
    </pet>
    <pet>
        <name>Blake</name>
        <age>12</age>
        <type>dog</type>
        <color>blue</color>
    </pet>
    <pet>
        <name>Loosey</name>
        <age>1</age>
        <type>cat</type>
        <color>brown</color>
    </pet>
    <pet>
        <name>Stop</name>
        <age>5</age>
        <type>pig</type>
        <color>brown</color>
    </pet>
</pets>
