=== shubham-aakarsh/APPDEV-LAB/lab3b/c.dtd
<!ELEMENT letter (date, addressee, greeting, paragraph, list, closing, signature, name)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT addressee (name, address_one, address_two)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address_one (#PCDATA)>
<!ELEMENT address_two (#PCDATA)>
<!ELEMENT greeting (#PCDATA)>
<!ELEMENT paragraph (#PCDATA)>
<!ELEMENT list (item+)>
<!ELEMENT item (#PCDATA)>
<!ELEMENT closing (#PCDATA)>
<!ELEMENT signature (#PCDATA)>





Convert the following XML document into an XHTML table using XSLT.  
 <? Xml version = ”1.0”  ?> 
       <? Xml : stylesheet type = ”text/xsl”  href = ”Students.xsl”  ?> 
          <Students> 
<Student> 
<name>John</name> 
<rollno>CS101</rollno> 
<department>CSE</department> 
<cgpa>9.5</cgpa> 
</Student> 
 <Student> 
<name>Williams</name> 
<rollno>CE034</rollno> 
<department>CIVIL</department> 
<cgpa>7.4</cgpa> 
</Student> 
<Student> 
<name>Rohit</name> 
<rollno>EC087</rollno> 
<department>ECE</department> 
<cgpa>8.7</cgpa> 
</Student> 
</Students>

=== shubham-aakarsh/APPDEV-LAB/lab3b/c.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE letter SYSTEM "c.dtd">
<letter>
    <date>December 11, 2002</date>
    <addressee>
        <name>Melvile Dewey</name>
        <address_one>Columbia University</address_one>
        <address_two>New York, NY</address_two>
    </addressee>
    <greeting>Dear Melvile,</greeting>
    <paragraph> I have been reading your ideas concerning the nature of librarianship, and I find
        them very intriguing. I would love the opportunity to discuss with you the role of the card
        catalog in today's libraries considering the advent to World Wide Web. Specifically, how are
        things like Google and Amazon.com changing our patrons' expectations of library services?
        Mr. Cutter and I will be discussing these ideas at the next Annual Meeting, and we are
        available at the following dates/times: </paragraph>
    <list>
        <item>Monday, 2-4</item>
        <item>Tuesday, 3-5</item>
        <item>Thursday, 1-3</item>
    </list>
    <closing>We hope you can join us.</closing>
    <signature>Sincerely,</signature>
    <name>James k Robert</name>
</letter>
