=== shubham-aakarsh/APPDEV-LAB/lab3a/d.dtd
<!ELEMENT Employee (Emp+)>
<!ELEMENT Emp (name, eid, department, doj, salary)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT eid (#PCDATA)>
<!ELEMENT department (#PCDATA)>
<!ELEMENT doj (#PCDATA)>
<!ELEMENT salary (#PCDATA)>

Write the DTD and XML Schema for the following XML document. 
<bank> 
</bank> 
<account account-number=“A-101” branch-name=“Downtown” 
balance=“500”> 
</account> 
<account account-number=“A-102” branch-name=“Perryridge” 
balance=“400”> 
</account> 
<account account-number=“A-201” branch-name=“Brighton” 
balance=“900”> 
</account> 
<customer customer-name=“Johnson” customer-street=“Alma” 
customer-city=“Palo Alto”> 
</customer> 
<customer customer-name=“Hayes” customer-street=“Main” 
customer-city=“Harrison”> 
</customer> 
<depositor account-number=“A-101” customer-name=“Johnson”> 
</depositor> 
<depositor account-number=“A-201” customer-name=“Johnson”> 
</depositor> 
<depositor account-number=“A-102” customer-name=“Hayes”> 
</depositor>

=== shubham-aakarsh/APPDEV-LAB/lab3a/d.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Employee SYSTEM "d.dtd">
<Employee>
  <Emp>
    <name>Roshan</name>
    <eid>E101</eid>
    <department>HR</department>
    <doj>09-SEP-1999</doj>
    <salary>68,000</salary>
  </Emp>
  <Emp>
    <name>Mary</name>
    <eid>E233</eid>
    <department>Accounts</department>
    <doj>06-AUG-2001</doj>
    <salary>24,000</salary>
  </Emp>
  <Emp>
    <name>Sunil</name>
    <eid>E521</eid>
    <department>Engineering</department>
    <doj>04-NOV-2009</doj>
    <salary>42,000</salary>
  </Emp>
</Employee>
